List VideosListData = [
  {
    "videoimage": "assets/images/videos1.png",
    "title": 'Animal husbandry and management',
    "text": 'Text of the printing and typesetting',
    "time": '5 min ago',
    "savevideo": 0,
    "route": '/videoslist',
  },
  {
    "videoimage": "assets/images/videos2.png",
    "title": 'Herd management and record-keeping',
    "text": 'Text of the printing and typesetting',
    "time": '5 min ago',
    "savevideo": 0,
    "route": '/videoslist',
  },
  {
    "videoimage": "assets/images/videos3.png",
    "title": 'Equipment and technology',
    "text": 'Text of the printing and typesetting',
    "time": '5 min ago',
    "savevideo": 0,
    "route": '/videoslist',
  },
  {
    "videoimage": "assets/images/videos4.png",
    "title": 'Marketing and business management',
    "text": 'Text of the printing and typesetting',
    "time": '5 min ago',
    "savevideo": 0,
    "route": '/videoslist',
  },
  {
    "videoimage": "assets/images/videos5.png",
    "title": 'Sustainable agriculture',
    "text": 'Text of the printing and typesetting',
    "time": '5 min ago',
    "savevideo": 0,
    "route": '/videoslist',
  },
  {
    "videoimage": "assets/images/videos6.png",
    "title": 'Animal welfare',
    "text": 'Text of the printing and typesetting',
    "time": '5 min ago',
    "savevideo": 0,
    "route": '/videoslist',
  },
];
